<?xml version="1.0" ?>
<testsuite errors="2" failures="0" name="Test-20190805002252" tests="3" time="0.008">
	<testcase classname="Test" name="test_nombre_casos_prueba" time="0.001"/>
	<testcase classname="Test" name="test_calcular_descuento_cliente_iniciales" time="0.004">
		<error message="local variable 'descuento' referenced before assignment" type="UnboundLocalError">
<![CDATA[Traceback (most recent call last):
  File "test.py", line 22, in test_calcular_descuento_cliente_iniciales
    mensaje, descuento = descuento.calcular_descuento(28,752,0)
UnboundLocalError: local variable 'descuento' referenced before assignment
]]>		</error>
	</testcase>
	<testcase classname="Test" name="test_calcular_descuento_cliente_jovenes" time="0.003">
		<error message="local variable 'descuento' referenced before assignment" type="UnboundLocalError">
<![CDATA[Traceback (most recent call last):
  File "test.py", line 17, in test_calcular_descuento_cliente_jovenes
    mensaje, descuento = descuento.calcular_descuento(19,502,0)
UnboundLocalError: local variable 'descuento' referenced before assignment
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
