<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="TestDescuentos-20190826092906" tests="10" time="0.001">
	<testcase classname="TestDescuentos" name="test_calcular_descuento_clientes_iniciales" time="0.000"/>
	<testcase classname="TestDescuentos" name="test_calcular_descuento_especiales" time="0.000"/>
	<testcase classname="TestDescuentos" name="test_calcular_descuento_familias" time="0.000"/>
	<testcase classname="TestDescuentos" name="test_calcular_descuento_familias_pequenias" time="0.000"/>
	<testcase classname="TestDescuentos" name="test_calcular_descuento_mayores_edad_1" time="0.000"/>
	<testcase classname="TestDescuentos" name="test_calcular_descuento_mayores_edad_2" time="0.000"/>
	<testcase classname="TestDescuentos" name="test_calcular_descuento_para_clientes_1" time="0.000"/>
	<testcase classname="TestDescuentos" name="test_calcular_descuento_para_clientes_2" time="0.000"/>
	<testcase classname="TestDescuentos" name="test_nombre_casos_prueba" time="0.000"/>
	<testcase classname="TestDescuentos" name="test_calcular_descuento_no_aplica" time="0.001">
		<error message="'Descuento para clientes' != 'No aplica'
- Descuento para clientes
+ No aplica
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "test.py", line 70, in test_calcular_descuento_no_aplica
    self.assertEqual(msj, msj_esperado)
AssertionError: 'Descuento para clientes' != 'No aplica'
- Descuento para clientes
+ No aplica

]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
